[advisories]
ignore = ["RUSTSEC-2024-0320", "RUSTSEC-2024-0436", "RUSTSEC-2025-0057", "RUSTSEC-2025-0046"]
informational_warnings = ["unmaintained"] # warn for categories of informational advisories
severity_threshold = "low" # CVSS severity ("none", "low", "medium", "high", "critical")
