[advisories]
ignore = ["RUSTSEC-2024-0320", "RUSTSEC-2024-0436", "RUSTSEC-2026-0006", "RUSTSEC-2026-0009", "RUSTSEC-2025-0057", "RUSTSEC-2025-0046", "RUSTSEC-2025-0118", "RUSTSEC-2025-0057", "RUSTSEC-2025-0111", "RUSTSEC-2026-0007", "RUSTSEC-2026-0020", "RUSTSEC-2026-0021", "RUSTSEC-2025-0141", "RUSTSEC-2025-0134"]
informational_warnings = ["unmaintained"] # warn for categories of informational advisories
severity_threshold = "low" # CVSS severity ("none", "low", "medium", "high", "critical")
